In [ ]:
import numpy as np

In [ ]:
data1 = [[2, 3, 4, 5], [3, 2, 1, 7]]
print(type(data1))
arr1 = np.array(data1)
print(arr1, type(arr1))

<class 'list'>
[[2 3 4 5]
 [3 2 1 7]] <class 'numpy.ndarray'>


In [ ]:
arr2 = np.sort(arr1)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr3 = np.hstack(arr2)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr4 = np.hstack(data1)
arr4

array([2, 3, 4, 5, 3, 2, 1, 7])

In [ ]:
data2 = []
arr5 = np.hstack(data2)
arr5

ValueError: ignored

In [ ]:
a = np.array([3, 2, 1, 10, 9, 8, 4, 5, 6, 7, 5, 
              5, 2, 3, 5, 6, 1, 2, 4, 5, 5]).flatten()
print(a.argmin(), a.min())
print(np.argwhere(a == 5))

2 1
[[ 7]
 [10]
 [11]
 [14]
 [19]
 [20]]


In [ ]:
b = np.argwhere(a==5)
print(b)
c = b.flatten()
print(c, ',' , len(c), c[0])

[[ 7]
 [10]
 [11]
 [14]
 [19]
 [20]]
[ 7 10 11 14 19 20] , 6 7


In [ ]:
f = a[np.argwhere(a==5).flatten()[0]]
f

5

In [11]:
import pandas as pd
import pickle

# 데이터 로드
data = pd.read_pickle('/content/drive/MyDrive/files/train_test_split.pkl')
data.keys()

dict_keys(['bounding_box_train\\0001_c2_f0046182.jpg', 'bounding_box_train\\0001_c2_f0046302.jpg', 'bounding_box_train\\0001_c2_f0046422.jpg', 'bounding_box_train\\0001_c2_f0046542.jpg', 'bounding_box_train\\0001_c2_f0046662.jpg', 'bounding_box_train\\0001_c2_f0046782.jpg', 'bounding_box_train\\0001_c2_f0046902.jpg', 'bounding_box_train\\0001_c2_f0047022.jpg', 'bounding_box_train\\0001_c5_f0051247.jpg', 'bounding_box_train\\0001_c5_f0051367.jpg', 'bounding_box_train\\0001_c5_f0051487.jpg', 'bounding_box_train\\0001_c5_f0051607.jpg', 'bounding_box_train\\0001_c5_f0051727.jpg', 'bounding_box_train\\0001_c5_f0051847.jpg', 'bounding_box_train\\0001_c6_f0030329.jpg', 'bounding_box_train\\0001_c6_f0030449.jpg', 'bounding_box_train\\0001_c6_f0030569.jpg', 'bounding_box_train\\0001_c6_f0030689.jpg', 'bounding_box_train\\0001_c6_f0030809.jpg', 'bounding_box_train\\0001_c6_f0030929.jpg', 'bounding_box_train\\0001_c6_f0031049.jpg', 'bounding_box_train\\0008_c1_f0044158.jpg', 'bounding_box_train\\

In [4]:
data_2 = pd.read_pickle('/content/drive/MyDrive/files/partitions.pkl')
data_2.keys()

dict_keys(['trainval_im_names', 'trainval_ids2labels', 'train_im_names', 'train_ids2labels', 'val_im_names', 'val_marks', 'test_im_names', 'test_marks'])

In [12]:
data

{'bounding_box_train\\0001_c2_f0046182.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\0001_c2_f0046302.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\0001_c2_f0046422.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\0001_c2_f0046542.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\0001_c2_f0046662.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\0001_c2_f0046782.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\0001_c2_f0046902.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\0001_c2_f0047022.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\0001_c5_f0051247.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\0001_c5_f0051367.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\0001_c5_f0051487.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\0001_c5_f0051607.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\0001_c5_f0051727.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\0001_c5_f0051847.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\0001_c6_f0030329.jpg': 'new_im_name_tmpl',
 'bounding_box_train\\000